excluded_cols = ["main_picture_url", "salvage", "savings_amount", "theft_title",
                 "trimId", "vehicle_damage_category", "cabin", "isCab", "is_certified",
                 "is_cpo", "is_oemcpo", "dealer_zip", "bed", "bed_height", "bed_length",
                 "combine_fuel_economy", "fleet", "frame_damaged"]

col_mappings = {
    "back_legroom": "Leg room in the rear seat: ",
    "body_type": "Type of the vehicle (Convertible, Hatchback etc.): ",
    "city": "City where the car is listed: ",
    "city_fuel_economy": "Fuel economy in city traffic in km/litre: ",
    "daysonmarket": "Days since the vehicle was first listed on the website: ",
    "description": "Vehicle description: ",
    "engine_cylinders": "Engine Cylinder configuration (i.e. I4, V6, etc.): ",
    "engine_displacement": "Cylinder volume swept by all of the pistons of a piston engine: ",
    "engine_type": "Engine type (i.e. I4, V6, etc.): ",
    "exterior_color": "Exterior dominant color of the vehicle: ",
    "franchise_dealer": "Whether the dealer is a franchise dealer: ",
    "franchise_make": "The company that owns the franchise: ",
    "front_legroom": "The legroom in inches for the passenger seat: ",
    "fuel_tank_volume": "Fuel tank's filling capacity in gallons: ",
    "fuel_type": "Dominant type of fuel ingested by the vehicle: ",
    "has_accidents": "Whether the vehicle has any accidents registered: ",
    "height": "Height of the vehicle in inches: ",
    "highway_fuel_economy": "Fuel economy in highway traffic in km/litre: ",
    "horsepower": "Horsepower (power produced by the engine): ",
    "interior_color": "Interior color: ",
    "is_new": "Was the vehicle launched less 2 years before 2020 (True / False): ",
    "latitude": "Latitude from the geolocation of the dealership: ",
    "length": "Length in inches: ",
    "listed_date": "The date the vehicle was listed: ",
    "listing_color": "Dominant color group from the exterior color: ",
    "listing_id": "The listing id: ",
    "longitude": "Longitude from the geolocation of the dealership: ",
    "major_options": "Main features: ",
    "make_name": "The company (make) that made the car: ",
    "maximum_seating": "Maximum seating: ",
    "mileage": "Mileage: ",
    "model_name": "The car's specific name (model): ",
    "owner_count": "No of previous owners: ",
    "power": "Power: ",
    "price": "Price (USD): ",
    "seller_rating": "Rating of the dealership: ",
    "sp_id": "Dealership id: ",
    "sp_name": "Dealership name: ",
    "torque": "Torque: ",
    "transmission": "Transmission: ",
    "transmission_display": "Transmission display: ",
    "trim_name": "Pre-packaged groups of features: ",
    "wheel_system": "Wheel system: ",
    "wheel_system_display": "Wheel system display: ",
    "wheelbase": "Horizontal distance between the centers of the front and rear wheels: ",
    "width": "Width in inches: ",
    "year": "Year available in market: ",
}
